version: "3.8"
services: 
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
       MYSQL_USER: yrden1
       MYSQL_PASSWORD: password1
       MYSQL_ROOT_PASSWORD: password1
       MYSQL_DATABASE: db
  app:
    build: .
    restart: always
    environment:
      WAIT_HOSTS: mysql:3306
      MYSQL_PASSWORD: password1
    ports:
      - '8080:8080'
    
